substitutions:
  _IMAGE: us-central1-docker.pkg.dev/$PROJECT_ID/openleash/docs-web:latest

steps:
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-f", "apps/docs-web/Dockerfile", "-t", "${_IMAGE}", "."]

images:
  - "${_IMAGE}"
